// Centralized mock data for development and testing
// This file contains all mock data used across components

export const mockStudents = [
  {
    id: 1,
    name: "Rahul Sharma",
    email: "rahul.sharma@email.com",
    phone: "+91 9876543210",
    roomNumber: "A-101",
    course: "B.Tech CSE",
    year: "3rd Year",
    status: "active",
    joinDate: "2024-01-15",
    photo: "/diverse-students.png",
    rentStatus: "paid",
  },
  {
    id: 2,
    name: "Priya Patel",
    email: "priya.patel@email.com",
    phone: "+91 9876543211",
    roomNumber: "B-205",
    course: "MBA",
    year: "1st Year",
    status: "active",
    joinDate: "2024-02-20",
    photo: "/diverse-female-student.png",
    rentStatus: "due",
  },
  {
    id: 3,
    name: "Amit Kumar",
    email: "amit.kumar@email.com",
    phone: "+91 9876543212",
    roomNumber: "C-102",
    course: "B.Sc Physics",
    year: "2nd Year",
    status: "active",
    joinDate: "2024-03-10",
    photo: "/male-student-studying.png",
    rentStatus: "paid",
  },
  {
    id: 4,
    name: "Anita Singh",
    email: "anita.singh@email.com",
    phone: "+91 9876543214",
    photo: "/diverse-female-student.png",
  },
  {
    id: 5,
    name: "Vikash Yadav",
    email: "vikash.yadav@email.com",
    phone: "+91 9876543215",
    photo: "/male-student-studying.png",
  },
  {
    id: 6,
    name: "Deepak Gupta",
    email: "deepak.gupta@email.com",
    phone: "+91 9876543216",
    photo: "/diverse-students.png",
  },
]

export const mockRooms = [
  {
    id: 1,
    number: "A-101",
    floor: 1,
    block: "A",
    type: "double",
    totalBeds: 2,
    occupiedBeds: 2,
    status: "occupied",
    rent: 8500,
    students: ["Rahul Sharma", "Amit Kumar"],
    availableBeds: [],
  },
  {
    id: 2,
    number: "A-102",
    floor: 1,
    block: "A",
    type: "double",
    totalBeds: 2,
    occupiedBeds: 1,
    status: "partial",
    rent: 8500,
    students: ["Priya Patel"],
    availableBeds: ["Bed 2"],
  },
  {
    id: 3,
    number: "A-103",
    floor: 1,
    block: "A",
    type: "double",
    totalBeds: 2,
    occupiedBeds: 0,
    status: "available",
    rent: 8500,
    students: [],
    availableBeds: ["Bed 1", "Bed 2"],
  },
  {
    id: 4,
    number: "B-201",
    floor: 2,
    block: "B",
    type: "single",
    totalBeds: 1,
    occupiedBeds: 0,
    status: "available",
    rent: 12000,
    students: [],
    availableBeds: ["Bed 1"],
  },
  {
    id: 5,
    number: "B-202",
    floor: 2,
    block: "B",
    type: "single",
    totalBeds: 1,
    occupiedBeds: 1,
    status: "occupied",
    rent: 12000,
    students: ["John Doe"],
    availableBeds: [],
  },
  {
    id: 6,
    number: "C-301",
    floor: 3,
    block: "C",
    type: "double",
    totalBeds: 2,
    occupiedBeds: 0,
    status: "available",
    rent: 8500,
    students: [],
    availableBeds: ["Bed 1"],
  },
]

export const mockBookings = [
  {
    id: 1,
    student: {
      name: "Rahul Sharma",
      email: "rahul.sharma@email.com",
      photo: "/diverse-students.png",
    },
    room: "A-101",
    bed: "Bed 1",
    checkIn: "2024-01-15",
    checkOut: null,
    monthlyRent: 8500,
    securityDeposit: 10000,
    nextRentDue: "2025-01-01",
    status: "active",
    totalPaid: 18500,
  },
  {
    id: 2,
    student: {
      name: "Priya Patel",
      email: "priya.patel@email.com",
      photo: "/diverse-female-student.png",
    },
    room: "B-205",
    bed: "Bed 2",
    checkIn: "2024-02-20",
    checkOut: null,
    monthlyRent: 8500,
    securityDeposit: 10000,
    nextRentDue: "2025-01-01",
    status: "active",
    totalPaid: 18500,
  },
  {
    id: 3,
    student: {
      name: "Amit Kumar",
      email: "amit.kumar@email.com",
      photo: "/male-student-studying.png",
    },
    room: "C-102",
    bed: "Bed 1",
    checkIn: "2024-03-10",
    checkOut: null,
    monthlyRent: 8500,
    securityDeposit: 10000,
    nextRentDue: "2025-01-01",
    status: "active",
    totalPaid: 18500,
  },
]

export const mockPendingStudents = [
  {
    id: 1,
    name: "Priya Patel",
    email: "priya.patel@email.com",
    photo: "/diverse-female-student.png",
    room: "B-205",
    monthlyRent: 8500,
    dueDate: "2024-12-01",
    daysOverdue: 15,
    lateFee: 500,
  },
  {
    id: 2,
    name: "Vikash Yadav",
    email: "vikash.yadav@email.com",
    photo: "/male-student-studying.png",
    room: "D-301",
    monthlyRent: 8500,
    dueDate: "2024-12-01",
    daysOverdue: 8,
    lateFee: 200,
  },
]

// Available rooms for booking
export const mockAvailableRooms = mockRooms.filter(room => 
  room.status === "available" || room.status === "partial"
).map(room => ({
  id: room.id,
  number: room.number,
  floor: room.floor,
  type: room.type,
  rent: room.rent,
  availableBeds: room.availableBeds,
}))

// Students available for new bookings (not currently assigned to rooms)
export const mockAvailableStudents = mockStudents.filter(student => 
  !student.roomNumber
)
